version: '3.7'

services:
  mongo:
    image: mongo
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    logging:
      driver: ${LOGGING_DRIVER:-local}
    networks:
      - default
    volumes:
      - ${APP_DATA_DIR}/mongo/data:/data/db
      - ${APP_DATA_DIR}/mongo/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  
  core:
    image: ghcr.io/mbecker20/komodo:${VERSION:-latest}
    labels:
      komodo.skip:
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: ${LOGGING_DRIVER:-local}
    networks:
      - default
    ports:
      - ${APP_PORT}:9120
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: ${DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${DB_PASSWORD}
      KOMODO_PASSKEY: ${PASSKEY}
      KOMODO_JWT_SECRET: ${PASSKEY}
      KOMODO_WEBHOOK_SECRET: ${PASSKEY}
      KOMODO_LOCAL_AUTH: "true"
      KOMODO_FIRST_SERVER: https://periphery:8120
    volumes:
      - ${APP_DATA_DIR}/repo-cache:/repo-cache

  periphery:
    image: ghcr.io/mbecker20/periphery:${VERSION:-latest}
    labels:
      komodo.skip:
    restart: unless-stopped
    logging:
      driver: ${LOGGING_DRIVER:-local}
    networks:
      - default
    environment:
      PERIPHERY_PASSKEYS: ${PASSKEY}
      PERIPHERY_SSL_ENABLED: "true"
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${APP_DATA_DIR}/ssl:/etc/komodo/ssl
      - ${APP_DATA_DIR}/repos:/etc/komodo/repos
      - ${APP_DATA_DIR}/stacks:/etc/komodo/stacks

networks:
  default: {}
